# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u5730\u5740')),
                ('port', models.IntegerField(default=9001, verbose_name='\u7aef\u53e3')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5bc6\u7801')),
                ('create_time', models.DateTimeField(verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('slug', models.CharField(max_length=40, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Supervisor\u914d\u7f6e',
                'verbose_name_plural': 'Supervisor\u914d\u7f6e',
            },
        ),
    ]
